{% set name = "sphinxcontrib-autoyaml" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib-autoyaml-{{ version }}.tar.gz
  sha256: 7be8cee5f2e1817b20007d20dad7ed0f3521c3ff57b7f77c0abff4224e6882c6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ruamel.yaml >=0.16.12
    - sphinx >=3.5.1

test:
  imports:
    - sphinxcontrib
  commands:
    - pip list | grep -E "{{ name }}\s+{{ version }}"
  requires:
    - pip
    - m2-grep  # [win]

about:
  home: https://github.com/Jakski/sphinxcontrib-autoyaml
  summary: Sphinx autodoc extension for documenting YAML files from comments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
